using Content.Client.UserInterface.Controls;
using Content.Shared.RussStation.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.RussStation.MedicalScanner;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerReagentWindow : FancyWindow
{
    public HealthAnalyzerReagentWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(HealthAnalyzerReagentState state)
    {
        TargetLabel.Text = Loc.GetString("health-analyzer-reagent-target-label", ("name", state.TargetName));
        GroupContainer.RemoveAllChildren();

        if (state.Groups.Count == 0)
        {
            GroupContainer.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-reagent-empty"),
                HorizontalAlignment = Control.HAlignment.Left,
            });
            return;
        }

        foreach (var group in state.Groups)
        {
            var box = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 2,
            };

            box.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-reagent-group-header",
                    ("label", group.Label),
                    ("volume", group.Volume.Float()),
                    ("max", group.MaxVolume.Float())),
                StyleClasses = { "LabelSubText" },
            });

            if (group.Reagents.Count == 0)
            {
                box.AddChild(new Label
                {
                    Text = Loc.GetString("health-analyzer-reagent-group-empty"),
                    Margin = new Robust.Shared.Maths.Thickness(8, 0, 0, 0),
                });
            }
            else
            {
                foreach (var reagent in group.Reagents)
                {
                    var line = new BoxContainer
                    {
                        Orientation = BoxContainer.LayoutOrientation.Horizontal,
                        Margin = new Robust.Shared.Maths.Thickness(8, 0, 0, 0),
                        HorizontalExpand = true,
                    };

                    line.AddChild(new PanelContainer
                    {
                        MinSize = new System.Numerics.Vector2(10, 10),
                        SetSize = new System.Numerics.Vector2(10, 10),
                        VerticalAlignment = Control.VAlignment.Center,
                        PanelOverride = new Robust.Client.Graphics.StyleBoxFlat
                        {
                            BackgroundColor = reagent.Color,
                        },
                    });

                    string locKey;
                    Robust.Shared.Maths.Color? color;
                    if (reagent.Overdose)
                    {
                        locKey = "health-analyzer-reagent-line-overdose";
                        color = Robust.Shared.Maths.Color.OrangeRed;
                    }
                    else if (reagent.Underdose)
                    {
                        locKey = "health-analyzer-reagent-line-underdose";
                        color = Robust.Shared.Maths.Color.SkyBlue;
                    }
                    else
                    {
                        locKey = "health-analyzer-reagent-line";
                        color = null;
                    }

                    line.AddChild(new Label
                    {
                        Text = Loc.GetString(locKey,
                            ("name", reagent.ReagentName),
                            ("quantity", reagent.Quantity.Float())),
                        Margin = new Robust.Shared.Maths.Thickness(6, 0, 0, 0),
                        FontColorOverride = color,
                    });

                    box.AddChild(line);
                }
            }

            GroupContainer.AddChild(box);
        }
    }
}
