using Content.Shared.RussStation.Skillchips;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.RussStation.Skillchips;

[GenerateTypedNameReferences]
public sealed partial class SkillchipStationWindow : DefaultWindow
{
    public event Action? OnImplant;
    public event Action? OnEject;
    public event Action<ProtoId<SkillchipPrototype>>? OnRemove;

    public SkillchipStationWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(SkillchipStationBoundUserInterfaceState state)
    {
        CapacityLabel.Text = Loc.GetString("skillchip-station-window-capacity-value",
            ("used", state.UsedCapacity),
            ("max", state.MaxCapacity));

        RebuildTray(state.InsertedChip, state.Working);
        RebuildImplanted(state.ImplantedChips, state.Working);
    }

    private void RebuildTray(SkillchipStationChipInfo? chip, bool working)
    {
        TrayContainer.RemoveAllChildren();

        if (chip == null)
        {
            TrayEmptyLabel.Visible = true;
            return;
        }

        TrayEmptyLabel.Visible = false;

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 6,
        };

        row.AddChild(new Label
        {
            Text = $"{chip.Name} ({chip.CapacityCost})",
            HorizontalExpand = true,
            ToolTip = chip.Description,
        });

        var implantBtn = new Button
        {
            Text = Loc.GetString("skillchip-station-window-implant"),
            Disabled = working,
        };
        implantBtn.OnPressed += _ => OnImplant?.Invoke();
        row.AddChild(implantBtn);

        var ejectBtn = new Button
        {
            Text = Loc.GetString("skillchip-station-window-eject"),
            Disabled = working,
        };
        ejectBtn.OnPressed += _ => OnEject?.Invoke();
        row.AddChild(ejectBtn);

        TrayContainer.AddChild(row);
    }

    private void RebuildImplanted(List<SkillchipStationChipInfo> chips, bool working)
    {
        ImplantedContainer.RemoveAllChildren();

        ImplantedEmptyLabel.Visible = chips.Count == 0;

        foreach (var chip in chips)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 6,
            };

            row.AddChild(new Label
            {
                Text = $"{chip.Name} ({chip.CapacityCost})",
                HorizontalExpand = true,
                ToolTip = chip.Description,
            });

            var removeBtn = new Button
            {
                Text = Loc.GetString("skillchip-station-window-remove"),
                Disabled = working,
            };
            var captured = chip.ChipProto;
            removeBtn.OnPressed += _ => OnRemove?.Invoke(captured);
            row.AddChild(removeBtn);

            ImplantedContainer.AddChild(row);
        }
    }
}
