# SPDX-FileCopyrightText: honksquad-ss14 contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Shared loading and shaping for the SS14 fork feature catalog.

`fork-features.yml` is the source of truth and is hand-editable. The renderers
(:mod:`build_page` for HTML, :mod:`build_markdown` for Markdown) both read it
through here so they cannot drift on what a "feature" or a "fork" is.
"""

from __future__ import annotations

from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
CATALOG = HERE / "fork-features.yml"
FIT = HERE / "fit.yml"

# How much of a fork's mapping has been through the second, corrected analysis
# pass. Granularity is not comparable across these, so both renderers surface it
# rather than presenting a half-refined catalog as uniform.
PASS_LABEL = {
    "refined": "refined pass",
    "round-1": "round-1 pass",
    "unmapped": "not yet mapped",
}

# Ordered worst-first, so a feature assessed several times can be summarised by
# its heaviest unit without either renderer inventing its own ranking.
ROUND_IMPACT = ("structural", "loop-change", "activity", "cosmetic")
GRAFT_SHAPE = ("entangled", "needs-upstream-edits", "drop-in")


def load(path: Path | None = None, fit: Path | None = None) -> dict:
    with (path or CATALOG).open(encoding="utf-8") as handle:
        catalog = yaml.safe_load(handle)
    _merge_fit(catalog, fit or FIT)
    _validate(catalog)
    return catalog


def _merge_fit(catalog: dict, path: Path) -> None:
    """Attach maintainer verdicts from fit.yml onto their features.

    Kept out of the catalog file itself because that one is regenerated by the
    Phase 2 tooling, which would silently drop hand-written judgement.
    """
    if not path.exists():
        return
    with path.open(encoding="utf-8") as handle:
        verdicts = (yaml.safe_load(handle) or {}).get("features") or {}

    by_id = {feature["id"]: feature for feature in catalog["features"]}
    unknown = set(verdicts) - set(by_id)
    if unknown:
        raise ValueError(f"{path.name} judges features that do not exist: {sorted(unknown)}")
    for fid, entry in verdicts.items():
        by_id[fid]["fit"] = entry.get("fit", "")
        by_id[fid]["fit_why"] = entry.get("why", "")


def _validate(catalog: dict) -> None:
    """Fail loudly on a malformed catalog rather than rendering a broken page."""
    for key in ("forks", "features"):
        if not catalog.get(key):
            raise ValueError(f"fork-features.yml has no {key}")

    known = {fork["id"] for fork in catalog["forks"]}
    for feature in catalog["features"]:
        if "implementations" in feature:
            raise ValueError(
                f"feature {feature['id']!r} still has an 'implementations' key — "
                "re-run assemble.py, which now emits 'authors' and 'carried_by'"
            )
        for row in authors(feature) + carriers(feature):
            if row["fork"] not in known:
                raise ValueError(
                    f"feature {feature['id']!r} references unknown fork {row['fork']!r}"
                )

    ids = {feature["id"] for feature in catalog["features"]}
    for feature in catalog["features"]:
        for entry in assessments(feature):
            for dep in entry.get("depends_on") or []:
                if dep not in ids:
                    raise ValueError(
                        f"assessment on {feature['id']!r} depends_on {dep!r}, "
                        "which is not a feature in this catalog"
                    )


def authors(feature: dict) -> list[dict]:
    """Forks that wrote this feature. These are the rows Phase 2 assesses."""
    return feature.get("authors") or []


def carriers(feature: dict) -> list[dict]:
    """Forks shipping another fork's copy of this feature.

    Never assessed — a carrier is the same code under a different roof. The
    count is the catalog's adoption signal, so it is reported, not judged.
    """
    return feature.get("carried_by") or []


def assessments(feature: dict) -> list[dict]:
    """Gameplay assessments, one per work-list unit.

    A feature can carry several: forks rarely build the "same" feature the same
    way, so divergent authors are assessed separately rather than averaged into
    one blurb that would be true of none of them.
    """
    return feature.get("assessments") or []


def verdict(entry: dict) -> dict | None:
    """The independent verification of an assessment, if one was run.

    `verified` is `False` on units no verifier ever saw. That is deliberately
    not the same as "checked and fine", and callers must not read it as such.
    """
    found = entry.get("verified")
    return found if isinstance(found, dict) else None


def graft_tier(entry: dict) -> str:
    """How far an assessment can actually be trusted as a graft recommendation.

    Only a verified unit can earn a tier. The verification pass refuted 8 of the
    10 units originally called `drop-in`, so an unverified claim of portability
    is a hypothesis, not a finding, and the shortlist must not rank on it.
    """
    checked = verdict(entry)
    if checked is None:
        return ""
    if checked.get("gameplay_supported") == "unsupported":
        return ""
    if entry.get("graft_shape") == "drop-in":
        return "take-now"
    # "Supported and not entangled" was calibrated when 35 units had verdicts
    # and it admitted 7. At full coverage the same rule admitted 74, roughly
    # half the catalog, which is not a recommendation. A candidate now has to
    # survive with NO refuted specific and come from an assessor who was not
    # hedging: both of those correlate with the unit actually being what it
    # says, and neither is satisfied by a merely long, confident-sounding
    # description.
    if (
        checked.get("gameplay_supported") == "supported"
        and not checked.get("overclaims")
        and entry.get("confidence") == "high"
        and entry.get("graft_shape") != "entangled"
    ):
        return "candidate"
    return ""


def eligible(feature: dict, entry: dict) -> bool:
    """Whether an assessment belongs on the shortlist at all.

    Two independent gates. The evidence has to hold up (`graft_tier`), and the
    feature has to be somewhere we want to go — a well-built, well-verified
    graft can still be the wrong direction, and that is the maintainer's call,
    not the analysis's.
    """
    return bool(graft_tier(entry)) and feature.get("fit") != "rejected"


def shortlist(catalog: dict) -> list[tuple[dict, dict]]:
    """(feature, assessment) pairs worth grafting, best first.

    This is the catalog's answer to "what should we take?", and it is short on
    purpose: everything in it survived a verifier whose job was to refute it.
    """
    rank = {"take-now": 0, "candidate": 1}
    rows = [
        (feature, entry)
        for feature in catalog["features"]
        for entry in assessments(feature)
        if eligible(feature, entry)
    ]
    rows.sort(
        key=lambda row: (
            row[0].get("fit") != "wanted",
            rank[graft_tier(row[1])],
            ROUND_IMPACT.index(row[1]["round_impact"]),
            -row[1].get("adoption", 0),
        )
    )
    return rows


def shortlist_by_feature(catalog: dict) -> list[tuple[dict, list[dict]]]:
    """The shortlist as one row per feature, its eligible units ranked inside.

    Several forks building the same thing is a comparison, not a repetition.
    Listing each unit flat made one feature look like several, and buried the
    question actually worth answering: whose version do we take?
    """
    grouped: dict[str, list[dict]] = {}
    for feature, entry in shortlist(catalog):
        grouped.setdefault(feature["id"], []).append(entry)
    by_id = {f["id"]: f for f in catalog["features"]}
    return [(by_id[fid], entries) for fid, entries in grouped.items()]


def rejected(catalog: dict) -> list[dict]:
    """Features ruled out by direction, with assessed units that would qualify.

    Recorded rather than deleted: the reason a good feature was passed over is
    the thing a future reader would otherwise re-derive from scratch.
    """
    return [
        feature
        for feature in catalog["features"]
        if feature.get("fit") == "rejected"
        and any(graft_tier(entry) for entry in assessments(feature))
    ]


def tag(fork: dict) -> str:
    """Column label for a fork.

    Forks identify each other by the namespace directory they claim in the tree
    (`_DV`, `_Goobstation`), so that is what the catalog labels them with.
    """
    namespaces = fork.get("namespaces") or []
    if namespaces:
        return namespaces[0].lstrip("_").upper()[:9]
    return fork["id"].replace("-", "").upper()[:9]


def categories(catalog: dict) -> list[str]:
    declared = catalog.get("categories")
    if declared:
        return declared
    return sorted({feature["category"] for feature in catalog["features"]})


def stats(catalog: dict) -> dict:
    features = catalog["features"]
    forks = catalog["forks"]
    passes = [fork.get("pass", "round-1") for fork in forks]
    rows = [row for f in features for row in authors(f) + carriers(f)]
    units = [entry for f in features for entry in assessments(f)]
    return {
        "forks": len(forks),
        "features": len(features),
        "authors": sum(len(authors(f)) for f in features),
        "carriers": sum(len(carriers(f)) for f in features),
        "impls": len(rows),
        "paths": sum(len(row.get("paths", [])) for row in rows),
        "refined": passes.count("refined"),
        "round1": passes.count("round-1"),
        "pending": passes.count("unmapped"),
        "assessed": len(units),
        "assessed_features": sum(1 for f in features if assessments(f)),
        "verified": sum(1 for entry in units if verdict(entry)),
        "corrected": sum(1 for entry in units if entry.get("graft_shape_claimed")),
        "shortlist": len(shortlist(catalog)),
    }
