using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.RussStation.Skillchips.Consumers.Kommand;

[GenerateTypedNameReferences]
public sealed partial class KommandColorPickerWindow : DefaultWindow
{
    /// <summary>Fired whenever the user moves a slider; the BUI relays each change to the server.</summary>
    public event Action<Color>? OnColorSelected;

    public KommandColorPickerWindow()
    {
        RobustXamlLoader.Load(this);
        ColorSelector.OnColorChanged += color => OnColorSelected?.Invoke(color);
    }

    /// <summary>Sync the slider state to the current authoritative color without re-firing OnColorChanged into a loop.</summary>
    public void SetColor(Color color)
    {
        if (ColorSelector.Color == color)
            return;

        ColorSelector.Color = color;
    }
}
