using Content.Shared.RussStation.Messenger;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.RussStation.Messenger;

[GenerateTypedNameReferences]
public sealed partial class MessengerCartridgeUiFragment : BoxContainer
{
    public event Action<NetEntity>? OnContactSelected;
    public event Action<NetEntity, string>? OnSendMessage;
    public event Action? OnBackPressed;
    public event Action? OnMuteToggled;

    private BoxContainer _contactList = default!;
    private readonly BoxContainer _chatView;
    private BoxContainer _messageList = default!;
    private LineEdit _messageInput = default!;
    private Button _sendButton = default!;
    private Button _backButton = default!;
    private readonly Button _muteButton;
    private readonly Label _addressLabel;

    private NetEntity? _activeTarget;

    // Cached lookup of the active conversation's contact, keyed by the conversation
    // it was resolved for, so repeated renders of the same conversation skip the
    // per-render O(n) scan of the contact list.
    private NetEntity? _cachedContactTarget;
    private string _cachedContactName = "";
    private bool _cachedContactReadOnly;

    public MessengerCartridgeUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;

        var content = (BoxContainer) GetChild(MessengerConstants.RootContentChildIndex);

        var contactScroll = BuildContactListSection();
        _chatView = BuildChatViewSection();

        _muteButton = new Button
        {
            ToggleMode = true,
            Text = Loc.GetString("messenger-mute"),
            StyleClasses = { "OpenBoth" },
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(MessengerConstants.MuteButtonLeftMargin, MessengerConstants.MuteButtonTopMargin, MessengerConstants.MuteButtonRightMargin, MessengerConstants.MuteButtonBottomMargin),
        };
        _muteButton.OnPressed += _ => OnMuteToggled?.Invoke();

        _addressLabel = new Label
        {
            StyleClasses = { "LabelSubText" },
            HorizontalAlignment = HAlignment.Right,
            Margin = new Thickness(MessengerConstants.AddressLabelLeftMargin, MessengerConstants.AddressLabelTopMargin, MessengerConstants.AddressLabelRightMargin, MessengerConstants.AddressLabelBottomMargin),
        };

        var body = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            VerticalExpand = true,
            HorizontalExpand = true,
        };
        body.AddChild(_muteButton);
        body.AddChild(contactScroll);
        body.AddChild(_chatView);

        content.AddChild(body);
        content.AddChild(_addressLabel);
    }

    /// <summary>
    /// Builds the scrollable contact-list view and captures <see cref="_contactList"/>.
    /// </summary>
    private ScrollContainer BuildContactListSection()
    {
        _contactList = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        var contactScroll = new ScrollContainer
        {
            VerticalExpand = true,
            HorizontalExpand = true,
        };
        contactScroll.AddChild(_contactList);

        return contactScroll;
    }

    /// <summary>
    /// Builds the (initially hidden) conversation view: back button, scrollable
    /// message list and the message input row.
    /// </summary>
    private BoxContainer BuildChatViewSection()
    {
        var chatView = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
            Visible = false,
        };

        _backButton = new Button
        {
            Text = Loc.GetString("messenger-back"),
            StyleClasses = { "OpenBoth" },
            HorizontalAlignment = HAlignment.Left,
            Margin = new Thickness(MessengerConstants.BackButtonLeftMargin, MessengerConstants.BackButtonTopMargin, MessengerConstants.BackButtonRightMargin, MessengerConstants.BackButtonBottomMargin),
        };
        _backButton.OnPressed += _ => OnBackPressed?.Invoke();

        _messageList = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        var messageScroll = new ScrollContainer
        {
            VerticalExpand = true,
            HorizontalExpand = true,
        };
        messageScroll.AddChild(_messageList);

        chatView.AddChild(_backButton);
        chatView.AddChild(messageScroll);
        chatView.AddChild(BuildInputRow());

        return chatView;
    }

    /// <summary>
    /// Builds the message input row and captures <see cref="_messageInput"/> and
    /// <see cref="_sendButton"/>.
    /// </summary>
    private BoxContainer BuildInputRow()
    {
        var inputRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(MessengerConstants.InputRowLeftMargin, MessengerConstants.InputRowTopMargin, MessengerConstants.InputRowRightMargin, MessengerConstants.InputRowBottomMargin),
        };

        _messageInput = new LineEdit
        {
            HorizontalExpand = true,
            PlaceHolder = Loc.GetString("messenger-placeholder"),
        };
        _messageInput.OnTextEntered += _ => SendCurrentMessage();

        _sendButton = new Button
        {
            Text = Loc.GetString("messenger-send"),
            StyleClasses = { "OpenBoth" },
            Margin = new Thickness(MessengerConstants.SendButtonLeftMargin, MessengerConstants.SendButtonTopMargin, MessengerConstants.SendButtonRightMargin, MessengerConstants.SendButtonBottomMargin),
        };
        _sendButton.OnPressed += _ => SendCurrentMessage();

        inputRow.AddChild(_messageInput);
        inputRow.AddChild(_sendButton);

        return inputRow;
    }

    public void UpdateState(MessengerUiState state)
    {
        _addressLabel.Text = state.Address;

        if (state.ActiveConversation != null)
        {
            ShowChatView(state);
        }
        else
        {
            ShowContactList(state);
        }
    }

    private void ShowContactList(MessengerUiState state)
    {
        _contactList.Visible = true;
        _chatView.Visible = false;
        _muteButton.Visible = true;
        _activeTarget = null;

        _muteButton.Pressed = state.Muted;
        _muteButton.Text = Loc.GetString(state.Muted ? "messenger-unmute" : "messenger-mute");

        HeaderLabel.Text = Loc.GetString("messenger-program-name");

        _contactList.RemoveAllChildren();

        if (!state.HasId)
        {
            _contactList.AddChild(CreateEmptyStateLabel("messenger-no-id"));

            if (state.Contacts.Count == 0)
                return;
        }

        if (state.Contacts.Count == 0)
        {
            _contactList.AddChild(CreateEmptyStateLabel("messenger-no-contacts"));
            return;
        }

        foreach (var contact in state.Contacts)
            _contactList.AddChild(CreateContactRowButton(contact));
    }

    private void ShowChatView(MessengerUiState state)
    {
        _contactList.Visible = false;
        _chatView.Visible = true;
        _muteButton.Visible = false;
        _activeTarget = state.ActiveConversation;

        ResolveActiveContact(state);

        HeaderLabel.Text = _cachedContactName;

        var canSend = !_cachedContactReadOnly && state.HasId;
        _messageInput.Visible = canSend;
        _sendButton.Visible = canSend;

        _messageList.RemoveAllChildren();

        if (state.Messages == null || state.Messages.Count == 0)
        {
            _messageList.AddChild(CreateEmptyStateLabel("messenger-no-messages"));
            return;
        }

        foreach (var msg in state.Messages)
            _messageList.AddChild(CreateMessageRow(msg));
    }

    /// <summary>
    /// Resolves the active conversation's display name and read-only flag, caching
    /// the result so subsequent renders of the same conversation avoid re-scanning
    /// the contact list.
    /// </summary>
    private void ResolveActiveContact(MessengerUiState state)
    {
        if (_cachedContactTarget == state.ActiveConversation)
            return;

        _cachedContactName = "";
        _cachedContactReadOnly = false;

        foreach (var contact in state.Contacts)
        {
            if (contact.Cartridge == state.ActiveConversation)
            {
                _cachedContactName = contact.Name;
                _cachedContactReadOnly = contact.ReadOnly;
                break;
            }
        }

        _cachedContactTarget = state.ActiveConversation;
    }

    private static Label CreateEmptyStateLabel(string locKey)
    {
        return new Label
        {
            Text = Loc.GetString(locKey),
            StyleClasses = { "LabelSubText" },
            HorizontalAlignment = HAlignment.Center,
        };
    }

    private Button CreateContactRowButton(MessengerContact contact)
    {
        var row = new Button
        {
            StyleClasses = { "OpenBoth" },
            HorizontalExpand = true,
            Margin = new Thickness(MessengerConstants.ContactRowLeftMargin, MessengerConstants.ContactRowTopMargin, MessengerConstants.ContactRowRightMargin, MessengerConstants.ContactRowBottomMargin),
        };

        var rowContent = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        rowContent.AddChild(new Label
        {
            Text = contact.Name,
            HorizontalExpand = true,
        });

        rowContent.AddChild(new Label
        {
            Text = contact.JobTitle,
            StyleClasses = { "LabelSubText" },
            Margin = new Thickness(MessengerConstants.JobLabelLeftMargin, MessengerConstants.JobLabelTopMargin, MessengerConstants.JobLabelRightMargin, MessengerConstants.JobLabelBottomMargin),
        });

        if (contact.HasUnread)
        {
            rowContent.AddChild(new Label
            {
                Text = "*",
                StyleClasses = { "LabelKeyValueStatValue" },
                Margin = new Thickness(MessengerConstants.UnreadDotLeftMargin, MessengerConstants.UnreadDotTopMargin, MessengerConstants.UnreadDotRightMargin, MessengerConstants.UnreadDotBottomMargin),
            });
        }

        row.AddChild(rowContent);

        var target = contact.Cartridge;
        row.OnPressed += _ => OnContactSelected?.Invoke(target);

        return row;
    }

    private static BoxContainer CreateMessageRow(MessengerMessageEntry msg)
    {
        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(MessengerConstants.MessageRowLeftMargin, MessengerConstants.MessageRowTopMargin, MessengerConstants.MessageRowRightMargin, MessengerConstants.MessageRowBottomMargin),
        };

        row.AddChild(new Label
        {
            Text = msg.SenderName,
            StyleClasses = { msg.FromSelf ? "LabelKeyValueStatValue" : "LabelSubText" },
        });

        row.AddChild(new Label
        {
            Text = msg.Text,
            HorizontalExpand = true,
        });

        return row;
    }

    private void SendCurrentMessage()
    {
        if (_activeTarget == null)
            return;

        var text = _messageInput.Text.Trim();
        if (string.IsNullOrEmpty(text))
            return;

        OnSendMessage?.Invoke(_activeTarget.Value, text);
        _messageInput.Text = "";
    }
}
