using Content.Shared.Atmos;
using Content.Shared.Atmos.EntitySystems;
using Content.Shared.Atmos.Piping.Portable.Components;
using Content.Shared.Atmos.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Atmos.UI;

[GenerateTypedNameReferences]
public sealed partial class PortableScrubberWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;

    public event Action<Gas>? OnGasToggled;

    private readonly Dictionary<Gas, CheckBox> _gasChecks = new();

    public PortableScrubberWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var atmosphereSystem = _entMan.System<SharedAtmosphereSystem>();

        foreach (var gas in Enum.GetValues<Gas>())
        {
            ProtoId<GasPrototype> gasProtoId = atmosphereSystem.GetGas(gas);
            var gasName = _prototypeManager.Index(gasProtoId).Name;

            var check = new CheckBox
            {
                Text = Loc.GetString(gasName),
                HorizontalExpand = true,
            };

            check.OnToggled += _ => OnGasToggled?.Invoke(gas);

            _gasChecks[gas] = check;
            GasContainer.AddChild(check);
        }
    }

    public void SetActive(bool active)
    {
        ToggleStatusButton.Pressed = active;
    }

    public void UpdateState(PortableScrubberBoundUserInterfaceState state)
    {
        ToggleStatusButton.Disabled = !state.Anchored;
        ToggleStatusButton.ToolTip = state.Anchored
            ? null
            : Loc.GetString("portable-scrubber-ui-not-anchored");

        foreach (var (gas, check) in _gasChecks)
            check.Pressed = state.FilterGases.Contains(gas);

        var fraction = state.MaxPressure > 0f ? state.Pressure / state.MaxPressure : 0f;
        PressureBar.Value = Math.Clamp(fraction, 0f, 1f);
        PressureLabel.Text = Loc.GetString("portable-scrubber-ui-pressure-value",
            ("pressure", (int) state.Pressure),
            ("max", (int) state.MaxPressure),
            ("percent", (int) Math.Round(fraction * 100)));
    }
}
