using Content.Shared.Atmos;
using Content.Shared.Atmos.EntitySystems;
using Content.Shared.Atmos.Piping.Portable.Components;
using Content.Shared.Atmos.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Atmos.UI;

[GenerateTypedNameReferences]
public sealed partial class PortableScrubberWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;

    public event Action<Gas>? OnGasToggled;

    private readonly Dictionary<Gas, Button> _gasButtons = new();

    public PortableScrubberWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var atmosphereSystem = _entMan.System<SharedAtmosphereSystem>();

        foreach (var gas in Enum.GetValues<Gas>())
        {
            ProtoId<GasPrototype> gasProtoId = atmosphereSystem.GetGas(gas);
            var gasName = _prototypeManager.Index(gasProtoId).Name;

            var button = new Button
            {
                Text = Loc.GetString(gasName),
                ToggleMode = true,
                HorizontalExpand = true,
            };

            button.OnToggled += _ =>
            {
                OnGasToggled?.Invoke(gas);
            };

            _gasButtons[gas] = button;
            GasContainer.AddChild(button);
        }
    }

    public void UpdateState(PortableScrubberBoundUserInterfaceState state)
    {
        foreach (var (gas, button) in _gasButtons)
        {
            button.Pressed = state.FilterGases.Contains(gas);
        }
    }
}
